// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var Crystal = Crystal || {};

/**
 * @constructor
 */
Crystal.BaseCmd = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Crystal.BaseCmd}
 */
Crystal.BaseCmd.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Crystal.BaseCmd=} obj
 * @returns {Crystal.BaseCmd}
 */
Crystal.BaseCmd.getRootAsBaseCmd = function(bb, obj) {
  return (obj || new Crystal.BaseCmd).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Crystal.BaseCmd.prototype.cmdid = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
Crystal.BaseCmd.prototype.ctrlid = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {number}
 */
Crystal.BaseCmd.prototype.buf = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
Crystal.BaseCmd.prototype.bufLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int8Array}
 */
Crystal.BaseCmd.prototype.bufArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Crystal.BaseCmd.startBaseCmd = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} cmdidOffset
 */
Crystal.BaseCmd.addCmdid = function(builder, cmdidOffset) {
  builder.addFieldOffset(0, cmdidOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ctrlid
 */
Crystal.BaseCmd.addCtrlid = function(builder, ctrlid) {
  builder.addFieldInt32(1, ctrlid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bufOffset
 */
Crystal.BaseCmd.addBuf = function(builder, bufOffset) {
  builder.addFieldOffset(2, bufOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Crystal.BaseCmd.createBufVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Crystal.BaseCmd.startBufVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Crystal.BaseCmd.endBaseCmd = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Crystal.BaseMsg = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Crystal.BaseMsg}
 */
Crystal.BaseMsg.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Crystal.BaseMsg=} obj
 * @returns {Crystal.BaseMsg}
 */
Crystal.BaseMsg.getRootAsBaseMsg = function(bb, obj) {
  return (obj || new Crystal.BaseMsg).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Crystal.BaseMsg.prototype.msgid = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
Crystal.BaseMsg.prototype.ctrlid = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {number}
 */
Crystal.BaseMsg.prototype.buf = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
Crystal.BaseMsg.prototype.bufLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int8Array}
 */
Crystal.BaseMsg.prototype.bufArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Crystal.BaseMsg.startBaseMsg = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} msgidOffset
 */
Crystal.BaseMsg.addMsgid = function(builder, msgidOffset) {
  builder.addFieldOffset(0, msgidOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ctrlid
 */
Crystal.BaseMsg.addCtrlid = function(builder, ctrlid) {
  builder.addFieldInt32(1, ctrlid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bufOffset
 */
Crystal.BaseMsg.addBuf = function(builder, bufOffset) {
  builder.addFieldOffset(2, bufOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Crystal.BaseMsg.createBufVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Crystal.BaseMsg.startBufVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Crystal.BaseMsg.endBaseMsg = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Crystal.GatewayBaseCmd = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Crystal.GatewayBaseCmd}
 */
Crystal.GatewayBaseCmd.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Crystal.GatewayBaseCmd=} obj
 * @returns {Crystal.GatewayBaseCmd}
 */
Crystal.GatewayBaseCmd.getRootAsGatewayBaseCmd = function(bb, obj) {
  return (obj || new Crystal.GatewayBaseCmd).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Crystal.GatewayBaseCmd.prototype.gatewayid = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Crystal.GatewayBaseCmd.prototype.clientid = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Crystal.GatewayBaseCmd.prototype.cmdid = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
Crystal.GatewayBaseCmd.prototype.ctrlid = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @returns {number}
 */
Crystal.GatewayBaseCmd.prototype.buf = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
Crystal.GatewayBaseCmd.prototype.bufLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int8Array}
 */
Crystal.GatewayBaseCmd.prototype.bufArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Crystal.GatewayBaseCmd.startGatewayBaseCmd = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} gatewayid
 */
Crystal.GatewayBaseCmd.addGatewayid = function(builder, gatewayid) {
  builder.addFieldInt16(0, gatewayid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} clientid
 */
Crystal.GatewayBaseCmd.addClientid = function(builder, clientid) {
  builder.addFieldInt32(1, clientid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} cmdidOffset
 */
Crystal.GatewayBaseCmd.addCmdid = function(builder, cmdidOffset) {
  builder.addFieldOffset(2, cmdidOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ctrlid
 */
Crystal.GatewayBaseCmd.addCtrlid = function(builder, ctrlid) {
  builder.addFieldInt32(3, ctrlid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bufOffset
 */
Crystal.GatewayBaseCmd.addBuf = function(builder, bufOffset) {
  builder.addFieldOffset(4, bufOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Crystal.GatewayBaseCmd.createBufVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Crystal.GatewayBaseCmd.startBufVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Crystal.GatewayBaseCmd.endGatewayBaseCmd = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Crystal.GatewayBaseMsg = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Crystal.GatewayBaseMsg}
 */
Crystal.GatewayBaseMsg.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Crystal.GatewayBaseMsg=} obj
 * @returns {Crystal.GatewayBaseMsg}
 */
Crystal.GatewayBaseMsg.getRootAsGatewayBaseMsg = function(bb, obj) {
  return (obj || new Crystal.GatewayBaseMsg).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
Crystal.GatewayBaseMsg.prototype.gatewayid = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt16(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
Crystal.GatewayBaseMsg.prototype.clientid = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Crystal.GatewayBaseMsg.prototype.msgid = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
Crystal.GatewayBaseMsg.prototype.buf = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
Crystal.GatewayBaseMsg.prototype.bufLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Int8Array}
 */
Crystal.GatewayBaseMsg.prototype.bufArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Crystal.GatewayBaseMsg.startGatewayBaseMsg = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} gatewayid
 */
Crystal.GatewayBaseMsg.addGatewayid = function(builder, gatewayid) {
  builder.addFieldInt16(0, gatewayid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} clientid
 */
Crystal.GatewayBaseMsg.addClientid = function(builder, clientid) {
  builder.addFieldInt32(1, clientid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} msgidOffset
 */
Crystal.GatewayBaseMsg.addMsgid = function(builder, msgidOffset) {
  builder.addFieldOffset(2, msgidOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bufOffset
 */
Crystal.GatewayBaseMsg.addBuf = function(builder, bufOffset) {
  builder.addFieldOffset(3, bufOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
Crystal.GatewayBaseMsg.createBufVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
Crystal.GatewayBaseMsg.startBufVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Crystal.GatewayBaseMsg.endGatewayBaseMsg = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Crystal.CmdConnectServ = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Crystal.CmdConnectServ}
 */
Crystal.CmdConnectServ.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Crystal.CmdConnectServ=} obj
 * @returns {Crystal.CmdConnectServ}
 */
Crystal.CmdConnectServ.getRootAsCmdConnectServ = function(bb, obj) {
  return (obj || new Crystal.CmdConnectServ).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Crystal.CmdConnectServ.prototype.servkey = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Crystal.CmdConnectServ.startCmdConnectServ = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} servkeyOffset
 */
Crystal.CmdConnectServ.addServkey = function(builder, servkeyOffset) {
  builder.addFieldOffset(0, servkeyOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Crystal.CmdConnectServ.endCmdConnectServ = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
Crystal.MsgCmdRet = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {Crystal.MsgCmdRet}
 */
Crystal.MsgCmdRet.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {Crystal.MsgCmdRet=} obj
 * @returns {Crystal.MsgCmdRet}
 */
Crystal.MsgCmdRet.getRootAsMsgCmdRet = function(bb, obj) {
  return (obj || new Crystal.MsgCmdRet).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
Crystal.MsgCmdRet.prototype.cmdid = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {boolean}
 */
Crystal.MsgCmdRet.prototype.isok = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
Crystal.MsgCmdRet.startMsgCmdRet = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} cmdidOffset
 */
Crystal.MsgCmdRet.addCmdid = function(builder, cmdidOffset) {
  builder.addFieldOffset(0, cmdidOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} isok
 */
Crystal.MsgCmdRet.addIsok = function(builder, isok) {
  builder.addFieldInt8(1, +isok, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
Crystal.MsgCmdRet.endMsgCmdRet = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// // Exports for Node.js and RequireJS
// this.Crystal = Crystal;
